##################################eureka\u914d\u7f6e#########################################
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    preferIpAddress: true
##################################\u9879\u76ee\u914d\u7f6e############################################
#uri\u4ee5lb://\u5f00\u5934\uff08lb\u4ee3\u8868\u4ece\u6ce8\u518c\u4e2d\u5fc3\u83b7\u53d6\u670d\u52a1\uff09\uff0c\u540e\u9762\u63a5\u7684\u5c31\u662f\u4f60\u9700\u8981\u8f6c\u53d1\u5230\u7684\u670d\u52a1\u540d\u79f0
consumer:
  uri: lb://service-api-consumer
consumer2:
  uri: lb://service-api-consumer2
  
spring:
  application:
    name: zebra-yritsz-gateway
  cloud:
    gateway:
      routes:
      - id: service-api-consumer
        uri: ${consumer.uri}
        predicates:
        - Path=/consumer/**
        filters:
              - StripPrefix=1 #\u53bb\u6389Path\u4e2d\u7b2c\u4e00\u4e2a\u8282\u70b9
              - name: Retry
                args:
                  retries: 2 #\u91cd\u8bd5\u6b21\u6570
      - id: service-api-consumer
        uri: ${consumer2.uri}
        predicates:
        - Path=/consumer2/**
        filters:
              - StripPrefix=1 #\u53bb\u6389Path\u4e2d\u7b2c\u4e00\u4e2a\u8282\u70b9
              - name: Retry
                args:
                  retries: 2 #\u91cd\u8bd5\u6b21\u6570
server:
  port: 1010

#logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG